# Generated by Django 5.0.6 on 2024-06-24 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0002_remove_webimagealbum_category_and_more'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='webimagealbum',
            name='cover',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cover', related_query_name='cover', to='images.webimage'),
        ),
    ]
