# Generated by Django 5.0.6 on 2024-06-24 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0003_webimagealbum_cover'),
        ('images', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='webimagealbum',
            name='images',
            field=models.ManyToManyField(blank=True, to='images.webimage'),
        ),
    ]
