# Generated by Django 5.0.6 on 2024-06-24 16:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0005_categoryalbum_tagalbum'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tagalbum',
            name='webimagealbum_ptr',
        ),
        migrations.DeleteModel(
            name='CategoryAlbum',
        ),
        migrations.DeleteModel(
            name='TagAlbum',
        ),
    ]
