# Generated by Django 5.0.6 on 2024-07-08 01:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0006_remove_tagalbum_webimagealbum_ptr_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webimagealbum',
            old_name='name',
            new_name='title',
        ),
    ]
