# Generated by Django 5.0.6 on 2024-06-20 03:45

import django.db.models.deletion
import images.models
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('name', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True)),
            ],
            options={
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Watermark',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.CharField(max_length=16)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('size', models.SmallIntegerField()),
                ('font', models.CharField(max_length=64)),
                ('transparency', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='WebImage',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(editable=False, max_length=64)),
                ('original', models.ImageField(editable=False, upload_to=images.models.WebImage._upload_to_base)),
                ('scaled', models.ImageField(blank=True, editable=False, null=True, upload_to=images.models.WebImage._upload_to_scaled)),
                ('thumbnail', models.ImageField(editable=False, upload_to=images.models.WebImage._upload_to_thumbnail)),
                ('date_modified', models.DateTimeField(auto_now=True)),
                ('date_created', models.DateTimeField(auto_now_add=True)),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='images.category')),
                ('tags', models.ManyToManyField(blank=True, to='images.tag')),
                ('uploader', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL)),
                ('watermark', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, to='images.watermark')),
            ],
        ),
    ]
