# Generated by Django 5.0.6 on 2024-07-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_remove_webimage_uploader'),
    ]

    operations = [
        migrations.AddField(
            model_name='webimage',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
