# Generated by Django 4.2.11 on 2024-06-15 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0002_alter_image_tags'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='tags',
            field=models.ManyToManyField(blank=True, to='images.tag'),
        ),
    ]
