# Generated by Django 5.0.6 on 2024-06-20 06:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('name', models.CharField(max_length=24, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
