upstream maierbox {
    server unix:/mnt/socket/gunicorn.sock fail_timeout=0;
}

server {
    
    listen 80;

    location = /metrics {
        return 404;
    }

    location / {
        proxy_pass http://maierbox;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location /static/ {
        alias /mnt/static/;
    }

    location /media/ {
        alias /mnt/media/;
    }

    location /media/images/private {
        deny all;
        return 403;
    }

    location /favicon.ico {
      alias /mnt/static/icons/favicon.ico;
    }

    client_max_body_size 1G;

}

server {
    listen 8080;

    location = /nginx_status {
        stub_status;
        access_log off;
    }

    location / {
        return 404;
    }
}

server {
    listen 9091;

    location = /django {
        proxy_pass http://maierbox/metrics;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location = /nginx {
        proxy_pass http://nginx_exporter:9113/metrics;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $host;
        proxy_redirect off;
    }

    location / {
        return 404;
    }
}