# Generated by Django 5.0.6 on 2024-12-08 10:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0003_webimage_unlisted'),
    ]

    operations = [
        migrations.RenameField(
            model_name='webimage',
            old_name='original',
            new_name='full',
        ),
    ]
