# Generated by Django 5.0.6 on 2024-12-08 10:42

import images.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('images', '0004_rename_original_webimage_full'),
    ]

    operations = [
        migrations.AddField(
            model_name='webimage',
            name='original',
            field=models.ImageField(blank=True, editable=False, null=True, upload_to=images.models.WebImage._upload_to_original),
        ),
    ]
