# Generated by Django 5.0.6 on 2024-06-24 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='webimagealbum',
            name='category',
        ),
        migrations.RemoveField(
            model_name='webimagealbum',
            name='modified_by',
        ),
        migrations.RemoveField(
            model_name='webimagealbum',
            name='tags',
        ),
        migrations.RemoveField(
            model_name='webimagealbum',
            name='uploader',
        ),
    ]
