# Generated by Django 5.0.6 on 2024-07-09 02:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('albums', '0007_rename_name_webimagealbum_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='webimagealbum',
            name='unlisted',
            field=models.BooleanField(default=False),
        ),
    ]
