# This workflow will build and push a new container image to Amazon ECR,
# and then will deploy a new task definition to Amazon ECS, when there is a push to the "main" branch.
#
name: Deploy to Amazon ECS

on:
  push:
    branches: [ "main" ]

env:
  AWS_REGION: us-east-2
  AWS_ROLE: arn:aws:iam::641334985368:role/MaierBoxGithubActions
  ECS_SERVICE: maierbox
  ECS_CLUSTER: maierbox

permissions:
  id-token: write
  contents: read

jobs:
  deploy:
    name: Deploy
    runs-on: self-hosted
    environment: production

    steps:
    - name: Checkout
      uses: actions/checkout@v4

    - name: Configure AWS credentials
      uses: aws-actions/configure-aws-credentials@v3
      with:
          role-to-assume: ${{ env.AWS_ROLE }}
          role-session-name: GitHub_to_AWS_via_FederatedOIDC
          aws-region: ${{ env.AWS_REGION }}

    - name: Login to Amazon ECR
      id: login-ecr
      uses: aws-actions/amazon-ecr-login@v1

    - name: Build, tag, and push MaierBox image to Amazon ECR
      id: build-maierbox
      working-directory: ./app
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build --platform linux/arm64 -t $ECR_REGISTRY/maierbox:$IMAGE_TAG -t $ECR_REGISTRY/maierbox:latest .
        docker push $ECR_REGISTRY/maierbox:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/maierbox:$IMAGE_TAG" >> $GITHUB_OUTPUT
    
    - name: Build, tag, and push nginx image to Amazon ECR
      id: build-nginx
      working-directory: ./nginx
      env:
        ECR_REGISTRY: ${{ steps.login-ecr.outputs.registry }}
        IMAGE_TAG: ${{ github.sha }}
      run: |
        # Build a docker container and
        # push it to ECR so that it can
        # be deployed to ECS.
        docker build --platform linux/arm64 -t $ECR_REGISTRY/nginx:$IMAGE_TAG -t $ECR_REGISTRY/nginx:latest .
        docker push $ECR_REGISTRY/nginx:$IMAGE_TAG
        echo "image=$ECR_REGISTRY/nginx:$IMAGE_TAG" >> $GITHUB_OUTPUT

    - name: Download task definition
      run: |
        aws ecs describe-task-definition --task-definition maierbox-ECSTaskDefinition-QBxVqZeWoBKM --query taskDefinition > task-definition.json

    - name: Fill in the new image ID for MaierBox in the Amazon ECS task definition
      id: def-maierbox
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: task-definition.json
        container-name: maierbox
        image: ${{ steps.build-maierbox.outputs.image }}
    
    - name: Fill in the new image ID for nginx in the Amazon ECS task definition
      id: def-nginx
      uses: aws-actions/amazon-ecs-render-task-definition@v1
      with:
        task-definition: ${{ steps.def-maierbox.outputs.task-definition }}
        container-name: nginx
        image: ${{ steps.build-nginx.outputs.image }}
      
    - name: Deploy Amazon ECS task definition
      uses: aws-actions/amazon-ecs-deploy-task-definition@v1
      with:
        task-definition: ${{ steps.def-nginx.outputs.task-definition }}
        service: ${{ env.ECS_SERVICE }}
        cluster: ${{ env.ECS_CLUSTER }}
        wait-for-service-stability: true
